apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
    tag: latest
  name: techtrends-staging
  namespace: {{ .values-staging.namespace.name }}
spec:
  ports:
  - port: 4111
    protocol: TCP
    targetPort: 3111
  selector:
    app: techtrends-staging
    tag: latest
  type: ClusterIP
